services:
  elasticsearch.helper:
            class: ElasticSearchBundle\Helper\ElasticSearchHelper
            arguments:
                - '%elastica_connections%'

  elasticsearch.doctrine.subscriber:
            class: ElasticSearchBundle\EventListener\ElasticSearchListener
            calls:
                - [ setEventDispatcher, ['@event_dispatcher'] ]
                - [ setElasticSearchHandler, ['@elasticsearch.handler'] ]
            tags:
                - { name: doctrine.event_subscriber }

  elasticsearch.handler:
              class: ElasticSearchBundle\Handler\ElasticSearchHandler
              arguments:
                - "@service_container"
                - "@elasticsearch.helper"
